FROM node:20 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Этап запуска статики
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html

# Если хочешь настроить nginx.conf — можно тоже добавить
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]