services:
  backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: run.py
    command: poetry run python run.py

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      REACT_APP_API_BASE_URL: http://localhost:3001
    command: npm start
