"""empty message

Revision ID: 52569ffa4124
Revises: d1e94f5917e7
Create Date: 2025-04-23 14:47:11.458976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52569ffa4124'
down_revision = 'd1e94f5917e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
