"""empty message

Revision ID: 72839546ff75
Revises: 08ea7dc27d89
Create Date: 2025-05-26 18:29:05.445467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72839546ff75'
down_revision = '08ea7dc27d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###
