"""empty message

Revision ID: ad33e1d3cb6a
Revises: 93fdec78f709
Create Date: 2025-05-26 14:09:30.121353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad33e1d3cb6a'
down_revision = '93fdec78f709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
