"""empty message

Revision ID: e5c2b09f8551
Revises: d7ed8b5e92b8
Create Date: 2025-05-13 18:19:29.307244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c2b09f8551'
down_revision = 'd7ed8b5e92b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_path', sa.String(length=200), nullable=True))
        batch_op.drop_column('media_ptah')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_ptah', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('media_path')

    # ### end Alembic commands ###
