"""empty message

Revision ID: f84ee2d1f93a
Revises: e5c2b09f8551
Create Date: 2025-05-26 13:18:27.779606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84ee2d1f93a'
down_revision = 'e5c2b09f8551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
