name: CI Pipeline

on:  
  push:  
    branches: [ main, dev ]  # Запускать на пуш в эти ветки  
  pull_request:  
    branches: [ main ]  # Запускать при PR в main  

jobs:
  test:  
    runs-on: ubuntu-latest  

    steps:
      - name: Клонирование репозитория  
        uses: actions/checkout@v3  

      - name: Установка Python  
        uses: actions/setup-python@v4  
        with:
          python-version: '3.13.1'  

      - name: Установка зависимостей  
        run: |  
          python -m pip install --upgrade pip  
          pip install poetry  
          poetry install  

      - name: Запуск тестов  
        run: |  
          poetry run pytest  
